export const GET_HOMEFEED = "GET_HOMEFEED";
export const GET_HOMEFEED_USER = "GET_HOMEFEED_USER";
export const GET_MORE_HOMEFEED = "GET_MORE_HOMEFEED";
export const LOADING_HOMEFEED = "LOADING_HOMEFEED";
export const LOADING_COMMENTS = "LOADING_COMMENTS";
export const GET_COMMENTS = "GET_COMMENTS";
export const UPLOAD_PHOTO = "UPLOAD_PHOTO";
export const PHOTO_SEARCHTEXT = "PHOTO_SEARCHTEXT";
