export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADING_FAIL = "USER_LOADING_FAIL";
export const USER_LOADED = "USER_LOADED";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
